library(ape)
library(testit)
phylogeny1 <- read.nexus(file = "Con_tree.nex")
phylogeny2 <- read.nexus(file = "MLL_tree.nex")
phylogeny3 <- read.nexus(file = "RNF213_tree.nex")
phylogeny4 <- read.nexus(file = "IRBP_tree.nex")
phylogeny5 <- read.nexus(file = "Rho_tree.nex")

# Phylogenies are not exactly the same
assert( all.equal(phylogeny1,phylogeny2,use.edge.length=FALSE))
assert( all.equal(phylogeny1,phylogeny3,use.edge.length=FALSE))
assert( all.equal(phylogeny1,phylogeny4,use.edge.length=FALSE))
assert( all.equal(phylogeny1,phylogeny5,use.edge.length=FALSE))
assert( all.equal(phylogeny2,phylogeny3,use.edge.length=FALSE))
assert( all.equal(phylogeny2,phylogeny4,use.edge.length=FALSE))
assert( all.equal(phylogeny2,phylogeny5,use.edge.length=FALSE))
assert( all.equal(phylogeny3,phylogeny4,use.edge.length=FALSE))
assert( all.equal(phylogeny3,phylogeny5,use.edge.length=FALSE))
assert( all.equal(phylogeny4,phylogeny5,use.edge.length=FALSE))
