sbatch ./job_0.sh
sbatch ./job_1.sh
sbatch ./job_2.sh
sbatch ./job_3.sh
sbatch ./job_4.sh
sbatch ./job_5.sh
sbatch ./job_6.sh
sbatch ./job_7.sh
sbatch ./job_8.sh
sbatch ./job_9.sh
sbatch ./job_10.sh
sbatch ./job_11.sh
sbatch ./job_12.sh
sbatch ./job_13.sh
sbatch ./job_14.sh
sbatch ./job_15.sh
sbatch ./job_16.sh
sbatch ./job_17.sh
sbatch ./job_18.sh
sbatch ./job_19.sh
sbatch ./job_20.sh
sbatch ./job_21.sh
sbatch ./job_22.sh
sbatch ./job_23.sh
sbatch ./job_24.sh
sbatch ./job_25.sh
sbatch ./job_26.sh
sbatch ./job_27.sh
sbatch ./job_28.sh
sbatch ./job_29.sh
sbatch ./job_30.sh
sbatch ./job_31.sh
sbatch ./job_32.sh
sbatch ./job_33.sh
sbatch ./job_34.sh
sbatch ./job_35.sh
sbatch ./job_36.sh